# 基础配置
style_image: img/xingkong.jpg  # 指定原始的风格图像
style_image_name: xingkong
naming: "wave"  # 这个模型的名字，一般和图像名保持一致。这个名字决定了checkpoint和events文件的保存文件夹
model_path: models  # checkpoint和events文件保存的根目录。最后所有的checkpoint和events文件会被保存在<model_path>/<wave>下

# 各个损失的权值
content_weight: 1.0  # 内容损失的权重
style_weight: 220.0  # 内容损失的权重
# style_weight: 220.0  # 风格损失的权重

image_size: 512  # 训练原始图片的大小
batch_size: 5  # 一次batch的样本数
epoch: 2  #

# 损失函数
loss_model: "vgg_16"  # 使用vgg_16模型
content_layers:  # 使用conv3_3定义内容损失
 - "vgg_16/conv3/conv3_3"
style_layers:  # 使用conv1_2、conv2_2、conv3_3、conv4_3定义风格损失
 - "vgg_16/conv1/conv1_2"
 - "vgg_16/conv2/conv2_2"
 - "vgg_16/conv3/conv3_3"
 - "vgg_16/conv4/conv4_3"
checkpoint_exclude_scopes: "vgg_16/fc"  # 只用到卷积层，所以不需要fc层
loss_model_file: "pretrained/vgg_16.ckpt"  # 预训练模型vgg_16.ckpt对应的位置







